# Generated by Django 4.2.7 on 2024-03-26 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_user_created_at_user_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
    ]
