# Generated by Django 4.2.7 on 2024-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
